/**
 * Ability file stem → zh label (from live roster paths 2026-09-21).
 * Keys match skillStem(path) — basename without .tres.
 */
export const SKILL_ZH: Record<string, string> = {
  GrabThrow: '抓取投掷',
  LifeDrain: '生命汲取',
  ShoulderCheck: '肩撞',
  SpearGoTroops: '长矛冲锋',
  SummonArcher: '召唤弓手',
  SummonSkeletonMage: '召唤骷髅法师',
  SummonSkeletonPriest: '召唤骷髅祭司',
  SummonWildling: '召唤蛮荒者',
  almighty_sanctuary: '全能圣域',
  apocalypse: '天启',
  archmage_element_1: '大法师元素 I',
  archmage_element_2: '大法师元素 II',
  archmage_element_3: '大法师元素 III',
  archmage_invoke: '大法师祈唤',
  baptizedbyfire: '火之洗礼',
  beast_trample: '野兽践踏',
  berserker_dash: '狂战冲刺',
  best_friend_pact: '挚友契约',
  black_mass: '暗黑弥撒',
  blazing_blink: '炽焰闪现',
  blink: '闪现',
  blink_strike: '闪击',
  blizzard: '暴风雪',
  blood_thunder: '血雷',
  bloodrage: '血怒',
  blows_of_furry: '怒击连打',
  boar_frenzy: '野猪狂乱',
  body_slam: '重摔',
  breath_of_bluefire: '蓝火吐息',
  breath_of_fire: '火焰吐息',
  call_wild_boar: '召唤野猪',
  chain_bond: '连锁羁绊',
  chain_heal: '连锁治疗',
  chain_lightning: '连锁闪电',
  chain_lightning_shaman: '萨满连锁闪电',
  choir_of_whispers: '低语合唱',
  conjurer_dash: '咒法师闪步',
  dark_aegis: '暗黑神盾',
  desperate_prayer: '绝望祈祷',
  divine_call: '神圣召唤',
  divine_transposition: '神圣换位',
  divine_vortex_templar: '圣殿漩涡',
  dragon_palm_rush: '龙掌突袭',
  echo_fireball: '回响火球',
  electrocute: '感电',
  ember_sparks_blessing: '余烬祝福',
  emberfall_basic_attack: '灰烬普攻',
  everwinter: '永冬',
  fire_comet: '火焰彗星',
  fireball: '火球术',
  firemage_dash: '火法闪步',
  firestorm: '火焰风暴',
  goblin_vanish: '哥布林隐遁',
  god_smite_templar: '神罚打击',
  gravity_well: '重力井',
  guided_hand: '引导之手',
  hammer_holy_spin: '圣锤旋风',
  hammerfall: '落锤',
  headbutt: '头槌',
  heavenly_jump_templar: '天堂跃击',
  heavy_dash: '重斩突进',
  holy_light: '圣光',
  holy_step: '圣步',
  holy_wrath: '神圣愤怒',
  hunter_shoot: '猎人射击',
  ice_apocalypse: '冰天启',
  ice_block: '寒冰屏障',
  ice_bolt: '冰箭',
  ice_dash: '寒冰闪步',
  ice_spike: '冰刺',
  immolation_blessing: '献祭祝福',
  inner_kinesis: '内劲',
  iron_skin: '铁皮',
  kick_dash: '踢突',
  leap_smash: '跃砸',
  lord_of_the_storm: '风暴之主',
  mage_dash: '法师闪步',
  mage_dash_alternative: '法师闪步(备选)',
  magic_heal: '魔法治疗',
  magnetic_tether: '磁力牵绊',
  manta_illusions: '幻影分身',
  mass_polymorph: '群体变形',
  medium_dash: '中距突进',
  mind_eclipse: '心智蚀日',
  mini_tornado: '小型龙卷',
  multiball: '多重火球',
  necro_dash: '死灵闪步',
  paladin_slash: '圣骑劈砍',
  parry_counter: '招架反击',
  pointdefense_turret: '点防炮塔',
  profane_resurrection: '渎神复活',
  reaper_beam: '收割射线',
  reaper_dash: '收割闪步',
  reaver_axe_volley: '掠夺者斧雨',
  reaver_heavy_axe_throw: '掠夺者重斧投掷',
  reaver_hop: '掠夺者跃击',
  reaver_throwing_axe: '掠夺者飞斧',
  reaver_tnt_axe: '掠夺者炸药斧',
  resurrection: '复活',
  rewind: '时光倒流',
  rise_like_the_phoenix: '凤凰重生',
  rogue_dash: '游侠闪步',
  rogue_ghost_mode: '游侠幽灵形态',
  sacred_mend: '神圣愈合',
  sanctuary: '圣域',
  shadow_dash: '暗影闪步',
  shadow_illusion: '暗影幻象',
  singularity_torpedo: '奇点鱼雷',
  slash: '劈砍',
  slash_monk: '武僧劈砍',
  slash_rogue_spellblade: '法刃劈砍',
  slash_thunderclaw: '雷爪劈砍',
  slash_warrior_barbarian: '蛮族劈砍',
  spear_thrust: '长矛突刺',
  stormfang: '风暴之牙',
  terrify: '恐惧',
  the_verdict: '裁决',
  thrust_assassin: '刺客突刺',
  thunder_attack: '雷击',
  thunder_step: '雷步',
  thunderclaw_dash: '雷爪突进',
  timesworn_clockbreaker: '时誓·破钟',
  timesworn_epoch_step: '时誓·纪元步',
  timesworn_final_hour: '时誓·终焉时刻',
  timesworn_pendulum_cleave: '时誓·摆锤劈',
  timesworn_zero_hour: '时誓·零点',
  titan_slam: '泰坦猛击',
  tornado: '龙卷风',
  tri_focus_beam: '三焦射线',
  umbral_scripture: '暗影经文',
  vampire_strike: '吸血打击',
  volt_shield: '伏特护盾',
  water_blast: '水波冲击',
  whirlwind_black: '黑色旋风',
  whirlwind_strike_black: '黑色旋风斩',
  wind_convergence: '风之汇聚',
  wind_step: '风步',
  // aliases / older keys
  grab_throw: '抓取投掷',
  shoulder_check: '肩撞',
  shattering_ram: '破城冲撞',
  battering_ram: '破城冲撞',
  thunder_storm: '雷暴'
}

/** Observed growth_styles keys on live dump (2026-09-21). */
export const GROWTH_STYLE_OPTIONS = [
  'balanced',
  'damage',
  'damage_excellent',
  'defense',
  'defense_excellent',
  'hp',
  'hp_excellent',
  'move_speed',
  'move_speed_excellent'
] as const

export type GrowthStyleId = (typeof GROWTH_STYLE_OPTIONS)[number]

export const GROWTH_STYLE_ZH: Record<string, string> = {
  balanced: '均衡',
  damage: '伤害',
  damage_excellent: '伤害(卓越)',
  defense: '防御',
  defense_excellent: '防御(卓越)',
  hp: '生命',
  hp_excellent: '生命(卓越)',
  move_speed: '移速',
  move_speed_excellent: '移速(卓越)',
  // legacy / unused fallbacks
  aggressive: '进攻',
  defensive: '防御',
  skirmisher: '游击',
  tank: '坦克',
  support: '辅助'
}
